name: file_utils
version: 0.1.4
description: File utils is a collection of the helper classes for file system.
homepage: https://github.com/mezoni/file_utils
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  globbing: ^0.3.0
  path: ^1.6.2
dev_dependencies:  
  pedantic: ^1.9.0
  test: any
